# 内部类
1. 成员内部类
2. 静态内部类
3. 局部内部类
4. 匿名内部类


/*
内部类可以直接访问外部类中成员,包括私有
外部类访问内部类,必须实例化内部类
*/
```java
class Outer{
    int x=3;
    class Inner{
        int x=4;
        void function(){
            int x=6;
                System.out.printf("inner"+Outer.this.x);
        }
    }

    void method(){
        System.out.printf(x);
    }
}


class InnerClassDemo{
    public static void main(String[] args) {
        //Outer out=new Outer();
        //out.method();

        //直接访问内部类中的成员
        Outer.Inner in=new Outer().new Inner();
        in.function();

    }
}

```

# 异常机制
问题也是现实生活中的一个具体事物,也可以通过Java 的类来描述,并分装成对象
其实就是 java 对不正常情况进行描述后的对象体现

出现问题结束运行

1. 严重问题  java 通过 ERROR 类进行描述 - 一般不针对代码进行处理
2. 非严重问题 java 通过 EXCEPTION 类进行描述 -进行针对代码处理


```java
// Throwable 类 查看 java API 文档
try{
    //被检测的代码 new Exception() 对象 发生后跳转到 catch
}catch(异常类 变量){  // 将被检测产生的 Exception 对象赋值给e= new 具体 Exception() 多态
    处理方式
    a.printStackTrace() // 其实 jvm 默认的 异常处理机制



}finally{
    一定会执行的语句;
}
```

在可能发生的方法上抛出异常 throws Exception 加上 这个的方法 一定要放到try catch 或 throws Exception

> 对多异常的处理
1. 进行具体的异常处理
2. 对面声明几个异常,就对应几个 catch 块 一般将异常信息放入到异常文件日志中


# 自定义异常
> 出现特定问题,并未被java 所描述并封装对象，
所以对于这些特有的问题可以按照java 的对问题封装的思想,
当在函数内部出现了 throw 抛出异常对象,那么就必须要给对应的处理动作。要么在内部 try catch<br>
要么在函数上声明让使用者调用

> 如何定义异常信息?
因为匪类中已经把异常信息的操作完成了.
因为自雷只要在构造时,将异常信息传给父类


# throws 和 throw
throws 在函数上,多个异常
throw 在函数内,异常对象


> Exception 中有一个特殊的子类异常 RuntimeException 运行时异常。
如果在函数内容抛出该异常,函数可以不用声明。

> 自定义异常时,如果该异常的发生,无法在继续进行运算,
就让自定义异常继承 RuntimeException

对于异常分两种
1. 编译时被检测的异常
2. 编译时不被检查的异常(运行时异常 RuntimeException 以及子类)
